//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUShopNearby2
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Tienda
    {


        [ScaffoldColumn(false)]
        public int idTienda { get; set; }
        public string Coordenadas { get; set; }
        public string Nombre { get; set; }
        public string R_Social { get; set; }
        public string N_Telefono { get; set; }
        public string Direccion { get; set; }
        public string Horario { get; set; }
        public Nullable<int> idPropietario { get; set; }
        public Nullable<int> idCiudad { get; set; }

        [JsonIgnore]
        public virtual Ciudad Ciudad { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
